"""Add walk-in support to appointments

Revision ID: 35627b999f1a
Revises: 
Create Date: 2025-10-17 14:33:43.900424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35627b999f1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_name', sa.String(length=100), nullable=True))
    op.add_column('appointments', sa.Column('client_phone', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('client_email', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('is_walk_in', sa.Boolean(), nullable=False))
    op.alter_column('appointments', 'client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'client_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'is_walk_in')
    op.drop_column('appointments', 'client_email')
    op.drop_column('appointments', 'client_phone')
    op.drop_column('appointments', 'client_name')
    # ### end Alembic commands ###
