"""add columns in notification

Revision ID: 463ca1b9e6ca
Revises: f7a11c6e1af3
Create Date: 2025-10-24 16:06:24.573863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463ca1b9e6ca'
down_revision: Union[str, Sequence[str], None] = 'f7a11c6e1af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
