"""add sent at column

Revision ID: f7a11c6e1af3
Revises: a21e6561f6e2
Create Date: 2025-10-24 14:36:51.940734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7a11c6e1af3'
down_revision: Union[str, Sequence[str], None] = 'a21e6561f6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'sent_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'sent_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
